

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/us-central1-docker.pkg.dev/faa-gcp-training-14-kfa-0808/ml-sales-prediction-rb', '.']

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/us-central1-docker.pkg.dev/faa-gcp-training-14-kfa-0808/ml-sales-prediction-rb']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ml-sales-prediction-application'
      - '--image'
      - 'gcr.io/us-central1-docker.pkg.dev/faa-gcp-training-14-kfa-0808/ml-sales-prediction-rb'
      - '--region'
      - 'us-central1' # Change as per your region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/us-central1-docker.pkg.dev/faa-gcp-training-14-kfa-0808/ml-sales-prediction'

options:
    logging: CLOUD_LOGGING_ONLY